### ISSUE TITLE
Only one side of LEDs turns on (lightpack + boblight + XMC)

### ISSUE THREAD

**Issue by Modix** [Atarity/Lightpack#84]
Hello,

I'm using lightpack for about a year. Since a few weeks only one side of the LEDs lights up. If I disconnect the USB cable and put it back again, all of the LEDs become available. Inserting USB after the PC has started seems also to work. Just rebooting the PC when only one side is working and USB is connected does not help. 

Others seem to have this problem too (http://forum.osmc.tv/showthread.php?tid=13210).

I've updated lightpack to the latest firmware without any luck. 

Is there anything that can be done about this, like inserting a delay or a reset into the firmware or the software?

Regards,

Oliver

**Comment by Atarity** [comment]
You should ask it thru [Lightpack.tv support](http://lightpack.tv/contact) . We (original Lightpack team) [out of the project](http://atarity.ru/post/85837330541/after-three-years-we-leave-our-lightpack) about a year. Up-to-date Lightpack repo was also [moved](https://github.com/woodenshark/Lightpack). :feelsgood:
